version: 0.2
 
batch:
   fast-fail: false
   build-fanout:
     parallelism: 3
     ignore-failure: false
 
phases:
   install:
     commands:
       - echo 'Install dependencies'
   pre_build:
     commands:
       - echo 'prebuild'
   build:
     commands:
       - echo 'Running JavaScript Tests'
       - codebuild-tests-run --test-command 'npx jest --runInBand --coverage' --files-search "codebuild-glob-search '**/tests/*.test.js'"

   post_build:
       commands:
         - echo 'Test execution completed'
