version: 0.2
 
batch:
   fast-fail: false
   build-fanout:
     parallelism: 3
     ignore-failure: false
 
phases:
   install:
     commands:
       - echo 'Install dependencies'
   pre_build:
     commands:
       - echo 'prebuild'
   build:
     commands:
       - echo 'Running JavaScript Tests'
       - echo $CODEBUILD_TOTAL_SHARDS
       - echo $CODEBUILD_CURRENT_SHARD
       - echo $(codebuild-glob-search '**/tests/*.js')
       - npx jest tests/add.test.js tests/divide.test.js --runInBand --coverage 
       - codebuild-tests-run --test-command 'Invoke-Expression "npx jest --runInBand --coverage $env:CODEBUILD_CURRENT_SHARD_FILES"' --files-search "codebuild-glob-search '**/tests/*.test.js'"

   post_build:
       commands:
         - echo 'Test execution completed'
